# Generated by Django 4.2.6 on 2023-11-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['slug'], name='list_list_slug_95efee_idx'),
        ),
    ]
