# Generated by Django 4.2.6 on 2023-11-08 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_list_slug_list_list_list_slug_95efee_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
