# Generated by Django 4.2.6 on 2023-11-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_list_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list.list'),
            preserve_default=False,
        ),
    ]
