version: "3.5"
services:
  db:
    image: 'postgres:13'
    container_name: 'db'
    networks:
      - backend
    env_file: ./env/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  tdd_learning:
    build: .
    container_name: 'tdd_learning'
    image: 'tdd_learning:1'
    command: >
      sh -c 'cd src &&
             poetry run python3 manage.py migrate --no-input &&
             poetry run python3 manage.py createadmin &&
             
             poetry run flake8 &&
             poetry run python3 manage.py check &&
             poetry run python3 manage.py test --no-input &&
             
             poetry run python3 manage.py runserver 0.0.0.0:8080'
    networks:
      - backend
    ports:
      - '8080:8080'
    volumes:
      - ./src:/service/src
      - app_static:/service/src/static
      - app_media:/service/src/media
    env_file:
      - ./env/.tdd_learning.env
    restart: unless-stopped
    depends_on:
      - db

networks:
  backend:

volumes:
  postgres_data:
  app_static:
  app_media:
